[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tokens = "4viYp2XpQ7fZoTgrnUHMxH9UyLa4bNYY1chcAykN39Mf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://xolana.xen.network"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
